version: '3.3'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "1"

services:
  hurado-main:
    container_name: hurado-main
    image: noiph/hurado:latest
    working_dir: /app
    command: npm run dev
    environment:
      - IS_UNDER_DOCKER=true
    env_file:
      - .env
    ports:
      - 127.0.0.1:10000:10000
    restart: always
    depends_on:
      - hurado-postgres
    links:
      - hurado-postgres
    volumes:
      - ./:/app/
      - /tmp/hurado-cache:/tmp/file-storage-cache
    networks:
      - internal-net
      - host-net
    logging: *default-logging
  hurado-judge:
    container_name: hurado-judge
    image: noiph/hurado:latest
    privileged: true
    working_dir: /app
    command: npm run dev:worker
    environment:
      - IS_UNDER_DOCKER=true
    env_file:
      - .env
    restart: always
    depends_on:
      - hurado-postgres
    links:
      - hurado-postgres
    volumes:
      - ./:/app/
      - /tmp/hurado-cache:/tmp/file-storage-cache
    networks:
      - internal-net
    logging: *default-logging
  hurado-postgres:
    container_name: hurado-postgres
    image: postgres:17-alpine
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data/
    networks:
      - internal-net
    logging: *default-logging
  hurado-redis:
    container_name: hurado-redis
    image: redis:7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379"  # Blob service
    volumes:
      - ./volumes/redis:/data
      - ./config/development/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - internal-net
    logging: *default-logging
  hurado-minio:
    container_name: hurado-minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=hurado
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio:/data
    networks:
      - internal-net
      - host-net
    logging: *default-logging

networks:
  internal-net:
    internal: true  # Restricts access to containers only
  host-net:
    internal: false
